#############################################################################
# Makefile for building: Symulator_UAR
# Generated by qmake (3.1) (Qt 6.5.3)
# Project:  Symulator_UAR.pro
# Template: app
# Command: D:\PC\Qt\6.5.3\msvc2019_64\bin\qmake.exe -o Makefile Symulator_UAR.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = D:\PC\Qt\6.5.3\msvc2019_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\PC\Qt\6.5.3\msvc2019_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\PC\Qt\6.5.3\msvc2019_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: Symulator_UAR.pro ..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\win32-msvc\qmake.conf ..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\spec_pre.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\common\windows-desktop.conf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\common\windows-vulkan.conf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\common\msvc-desktop.conf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\qconfig.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_ext_freetype.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_ext_libjpeg.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_ext_libpng.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_charts.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_chartsqml.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_chartsqml_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_core.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_entrypoint_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_example_icons_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_freetype_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_harfbuzz_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_help.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_jpeg_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsanimation.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsanimation_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssettings.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssettings_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_linguist.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_linguist_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_network.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_png_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlcore.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlcore_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmldom_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickeffects_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_tools_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\qt_functions.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\qt_config.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\win32-msvc\qmake.conf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\spec_post.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\exclusive_builds.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\common\msvc-version.conf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\toolchain.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\default_pre.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\win32\default_pre.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\resolve_config.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\default_post.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\qml_debug.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\entrypoint.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\precompile_header.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\warn_on.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\qt.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\resources_functions.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\resources.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\moc.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\win32\opengl.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\uic.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\qmake_use.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\file_copies.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\win32\windows.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\testcase_targets.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\exceptions.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\yacc.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\lex.prf \
		Symulator_UAR.pro \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Charts.prl \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6OpenGLWidgets.prl \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Widgets.prl \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6OpenGL.prl \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Gui.prl \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Network.prl \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Core.prl \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6EntryPoint.prl \
		.qmake.stash \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\build_pass.prf \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Chartsd.prl \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6OpenGLWidgetsd.prl \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Widgetsd.prl \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6OpenGLd.prl \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Guid.prl \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Networkd.prl \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Cored.prl \
		..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6EntryPointd.prl
	$(QMAKE) -o Makefile Symulator_UAR.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\spec_pre.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\common\windows-desktop.conf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\common\windows-vulkan.conf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\common\msvc-desktop.conf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\qconfig.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_ext_freetype.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_ext_libjpeg.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_ext_libpng.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_charts.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_chartsqml.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_chartsqml_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_core.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_designer.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_entrypoint_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_example_icons_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_freetype_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_gui.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_harfbuzz_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_help.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_jpeg_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsanimation.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsanimation_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssettings.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssettings_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_linguist.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_linguist_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_network.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_png_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qml.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlcore.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlcore_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmldom_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickeffects_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sql.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svg.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_tools_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_xml.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\qt_functions.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\qt_config.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\win32-msvc\qmake.conf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\spec_post.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\exclusive_builds.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\common\msvc-version.conf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\toolchain.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\default_pre.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\win32\default_pre.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\resolve_config.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\exclusive_builds_post.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\default_post.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\qml_debug.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\entrypoint.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\precompile_header.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\warn_on.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\qt.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\resources_functions.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\resources.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\moc.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\win32\opengl.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\uic.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\qmake_use.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\file_copies.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\win32\windows.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\testcase_targets.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\exceptions.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\yacc.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\lex.prf:
Symulator_UAR.pro:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Charts.prl:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6OpenGLWidgets.prl:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Widgets.prl:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6OpenGL.prl:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Gui.prl:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Network.prl:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Core.prl:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6EntryPoint.prl:
.qmake.stash:
..\..\..\PC\Qt\6.5.3\msvc2019_64\mkspecs\features\build_pass.prf:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Chartsd.prl:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6OpenGLWidgetsd.prl:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Widgetsd.prl:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6OpenGLd.prl:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Guid.prl:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Networkd.prl:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6Cored.prl:
..\..\..\PC\Qt\6.5.3\msvc2019_64\lib\Qt6EntryPointd.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Symulator_UAR.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
	-$(DEL_FILE) Symulator_UAR.vc.pdb
	-$(DEL_FILE) Symulator_UAR.ilk
	-$(DEL_FILE) Symulator_UAR.idb
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash Symulator_UAR.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
